### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by arnaudmorvan** [Pixate/Titanium-PixateFreestyle#1]
Hello,

I try to create the zip from build.py but I get an error of type:

*\* BUILD FAILED **
The following build commands failed:
CompileC build/PXEngine.build/Release-iphoneos/PXEngine.build/Objects-normal/armv7/ComPixatePxengineModule.o Classes/ComPixatePxengineModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

What should I do ?
Thank you!

**Comment by thelonious** [comment]
Arnaurd,

What version of Xcode are you building with? Also, we've seen build issues related to the version of node that you have installed. What version are you using there as well?

Thanks,
Kevin

**Comment by arnaudmorvan** [comment]
Hello thank you for your answer!
I compile with Xcode 4.6 and I tried the sdk 2.1.4.GA, 3.0.0.GA and 3.2.0.

thank you
Arnaud

**Comment by thelonious** [comment]
Arnaud,

Can you run this on the command-line "node --version" to see what version of node you are using? We have had issues internally building when using newer versions node. That may be related.

Also, did you make the symbolic link inside PXEngine?

```
cd PXEngine
ln -s ~/Desktop/Pixate/Frameworks/PXEngine.framework ./PXEngine.framework
```

-Kevin

**Comment by arnaudmorvan** [comment]
I have the v0.8.22 release.
Yes I made the symbolic link link inside PXEngine

**Comment by thelonious** [comment]
Arnaud,

We've been able to recreate a similar error when the soft-link is not setup properly. I know you've setup the link, but just to be doubly sure, here's how I've setup my build:
- I downloaded the Pixate DMG file, opened it, and copied the Pixate folder to my desktop
- I cloned the Titanium-Pixate repo
- I changed my current directory to Titanium-Pixate/PXEngine
- I ran the following in the terminal: ln -s ~/Desktop/Pixate/Frameworks/PXEngine.framework ./PXEngine.framework

When I "ls -alFG" the PXEngine directory, I see this entry:

```
PXEngine.framework@ -> /Users/kevin/Desktop/Pixate/Frameworks/PXEngine.framework
```

I'm also running node.js 0.10.4, but I can't see how that would affect CompileC.

**Comment by arnaudmorvan** [comment]
Thank you,
I still have the same error. I still updated node.js.

**Comment by thelonious** [comment]
Arnaud,

(sigh) It has to be something simple we're missing. Do you have the Command Line Tools installed from Xcode?

**Comment by yamill** [comment]
I'm having the same issue as well. I've followed all the correct steps and I receive the error:

The following build commands failed:
    CompileC build/PXEngine.build/Release-iphoneos/PXEngine.build/Objects-normal/armv7/ComPixatePxengineModule.o Classes/ComPixatePxengineModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild failed

**Comment by yamill** [comment]
My node version is v0.10.13

**Comment by yamill** [comment]
@thelonious @arnaudmorvan were you able to resolve?

**Comment by yamill** [comment]
@arnaudmorvan @thelonious I found the issue! there was a typo in the path. it now builds successfully! 

ln -s ~/Desktop/Pixate/Frameworks/PXEngine.framework ./PXEngine.framework

needs to be changed to

ln -s ~/Desktop/Pixate/Framework/PXEngine.framework ./PXEngine.framework

**Comment by thelonious** [comment]
Yamill,

Awesome! And good catch. Since we no longer include the 3rd-party builds in the installer, the directory changed from Frameworks to Framework. I've pushed the change to the README.

-Kevin

**Comment by khrichtchatyi** [comment]
I changed to ln -s ~/Desktop/Pixate/Framework/PXEngine.framework ./PXEngine.framework but I have error:

The following build commands failed:
    CompileC build/PXEngine.build/Release-iphoneos/PXEngine.build/Objects-normal/armv7/ComPixatePxengineModule.o Classes/ComPixatePxengineModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild failed

node --version v0.10.17
titanium sdk 3.1.2.G.A
xcode 4.6.3

**Comment by khrichtchatyi** [comment]
Before compiling: Close xCode & Titanium 
Please write about this in readme file

**Comment by lalu5585** [comment]
hey,

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   CompileC build/CaptureSpeak.build/Debug-iphonesimulator/CaptureSpeak.build/Objects-normal/i386/TiSnapBehavior.o Classes/TiSnapBehavior.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] :  (1 failure)

can you helpme to solve it??what wasthe problem.ididn'tget it..

**Comment by khrichtchatyi** [comment]
Close xCode & Titanium before compiling
